name: Docker Image Build and Push
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
     
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: '${{ secrets.DOCKERHUB_USERNAME }}'
          password: '${{ secrets.DOCKERHUB_TOKEN }}'
          
      - name: build image
        run: docker build -t timlefever/pe-opsy-frontend .
      - name: push to dockerhub
        run: docker push timlefever/pe-opsy-frontend
