name: Docker Image Build and Push
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11' 

      - name: Update version
        run: mvn -B versions:set -DnewVersion=v${{github.run_number}} -DgenerateBackupPoms=false
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
     
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: '${{ secrets.DOCKERHUB_USERNAME }}'
          password: '${{ secrets.DOCKERHUB_TOKEN }}'
      - name: build image
        run: docker build -t timlefever/pe-opsy-frontend .
      - name: push to dockerhub
        run: docker push timlefever/pe-opsy-frontend
